# Generated by Django 5.1.1 on 2024-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_adminuser_adminborrowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_from',
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
